# Generated by Django 5.2.9 on 2026-03-13 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_alter_user_is_active_auditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalidentifier',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.clientsystem'),
        ),
    ]
