# Generated by Django 5.2.9 on 2026-03-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_externalidentifier_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
