# Generated by Django 5.2.9 on 2026-03-13 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_name_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantee_type', models.CharField(choices=[('user', 'User'), ('client', 'Client System')], max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('grantee_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_access_grants', to='users.clientsystem')),
                ('grantee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_access_grants', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='users.name')),
            ],
            options={
                'unique_together': {('name', 'grantee_client'), ('name', 'grantee_user')},
            },
        ),
    ]
