# Generated by Django 5.2.9 on 2026-03-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_clientsystem_registered_at_clientsystem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsystem',
            name='permissions',
            field=models.CharField(blank=True, choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], max_length=50, null=True),
        ),
    ]
