# Generated by Django 5.2.9 on 2026-03-16 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_clientsystem_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsystem',
            name='permissions',
        ),
    ]
